# Generated by Django 5.2.4 on 2025-07-10 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(choices=[('caba', 'Capital Federal'), ('franja1', 'Franja 1'), ('franja2', 'Franja 2'), ('franja3', 'Franja 3')], max_length=255, verbose_name='Destino')),
                ('nro_seguimiento', models.CharField(max_length=50, unique=True, verbose_name='Número de seguimiento')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, verbose_name='Estado del envío')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancho (cm)')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alto (cm)')),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Largo (cm)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
    ]
